name: Parse BIS Lists

on:
  # Allow manual trigger
  workflow_dispatch:
  # Trigger daily at 05:00 PDT
  schedule:
    - cron: '0 12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r tools/requirements.txt
      
      - name: Run tools/install-chrome.sh
        run: |
          pwd
          cd tools/
          ./install-chrome.sh
          cd ..
      
      - name: Run parse-wowhead.py
        run: |
          cp data/wowhead.json data/wowhead.json.old
          python tools/parse-wowhead.py

      - name: Check for changes
        id: check_changes
        run: |
          # Check if wowhead.json has changed
          echo "Checking for changes in wowhead.json"
          diff_output=$(diff data/wowhead.json data/wowhead.json.old || true)

          # Check if the diff_output variable is empty
          if [ -z "$diff_output" ]
          then
              # If it is empty, the files are identical
              echo "No changes detected"
              echo "changed=false" >> $GITHUB_OUTPUT
          else
              # If it is not empty, the files are different
              echo "There are pending changes to wowhead.json"
              echo "changed=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Exit if no changes
        if: steps.check_changes.outputs.changed != 'true'
        run: |
          echo "No changes detected, exiting"
          exit 0
      
      - name: Generate loot table
        if: steps.check_changes.outputs.changed != 'false'
        run: python tools/generate-loot-table.py

      # - name: Generate next tag
      #   id: gen_tag
      #   if: steps.check_changes.outputs.changed != 'false'
      #   uses: anothrNick/github-tag-action@1.64.0 # Don't use @master or @v1 unless you're happy to test the latest version
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # if you don't want to set write permissions use a PAT token
      #     WITH_V: false
      #     DRY_RUN: true # Allows for capturing the proposed tag (new_tag output)
      # 
      # - name: Generate changelog
      #   id: generate_changelog
      #   if: steps.check_changes.outputs.changed != 'false'
      #   run: |
      #     python tools/generate-changelog.py
      # 
      #     # Multi-line output
      #     changelogoutput=$(cat changelog.md.tmp)
      #     echo "Changelog: $changelogoutput"
      #     echo "Writing to GitHub output"
      # 
      #     # Write changelog to GitHub output
      #     EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
      #     echo "changelog<<$EOF" >> $GITHUB_OUTPUT
      #     echo "$changelogoutput" >> $GITHUB_OUTPUT
      #     echo "$EOF" >> $GITHUB_OUTPUT
      # 
      #     # Write changelog to changelog-latest.md
      #     cp changelog.md.tmp changelog-latest.md
      # 
      # - name: Bump toc version
      #   if: steps.check_changes.outputs.changed != 'false'
      #   run: |
      #     # Use sed to modify the '## Version: 0.0.1' line in SOD_BISListTooltip.toc to instead be '## Version: ${{ steps.gen_tag.outputs.new_tag }}'
      #     sed -i "s/## Version: .*/## Version: ${{ steps.gen_tag.outputs.new_tag }}/g" SOD_BISListTooltip.toc
      
      - name: Create pull request
        if: steps.check_changes.outputs.changed != 'false'
        uses: peter-evans/create-pull-request@v5
        with:
          add-paths: 'data/wowhead.json,WowheadLootTable.lua,SOD_BISListTooltip.toc,changelog-latest.md'
          commit-message: Update BIS lists
          title: Update BIS lists
          body: |
            ${{ steps.generate_changelog.outputs.changelog }}
          branch: update-bis-lists
          reviewers: JoVoCop
          delete-branch: true

      # Automatically merge pull request - Disabled until we gain confidence
      # - name: Auto merge pull request
      #   run: gh pr merge --merge --auto "${{ steps.generate_changelog.outputs.pull-request-number }}"