name: Parse BIS Lists

on:
  # Allow manual trigger
  workflow_dispatch:
  # Trigger daily at 00:00 UTC
  #schedule:
  #  - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r tools/requirements.txt
      
      # Testing
      # - name: Run tools/install-chrome.sh
      #   run: |
      #     pwd
      #     cd tools/
      #     ./install-chrome.sh
      #     cd ..
      
      - name: Run parse-wowhead.py
        run: |
          cp data/wowhead.json data/wowhead.json.old
          cp data/wowhead.json.new data/wowhead.json
          # Testing
          # python tools/parse-wowhead.py

      - name: Check for changes
        id: check_changes
        run: |
          git diff --quiet || echo "changed=true" >> $GITHUB_OUTPUT
      
      - name: Exit if no changes
        if: steps.check_changes.outputs.changed != 'true'
        run: |
          echo "No changes detected, exiting"
          exit 0
      
      - name: Generate loot table
        run: python tools/generate-loot-table.py

      - name: Generate changelog
        id: generate_changelog
        run: |
          python tools/generate-changelog.py

          # Multi-line output
          delimiter="$(openssl rand -hex 8)"
          echo "changelog<<${delimiter}" >> "${GITHUB_OUTPUT}"
          cat changelog.md.tmp >> "${GITHUB_OUTPUT}"
          echo "${delimiter}" >> "${GITHUB_OUTPUT}"

      
      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          add-paths: 'data/wowhead.json,WowheadLootTable.lua'
          commit-message: Update BIS lists
          title: Update BIS lists
          body: |
            ${{ steps.generate_changelo.outputs.changelog }}
          branch: update-bis-lists
          delete-branch: true